TICKERS = {
    "^GSPC": "S&P 500",
    "^IXIC": "NASDAQ Composite",
    "^RUT": "Russell 2000",
    "^FTSE": "FTSE 100",
    "^STOXX50E": "Euro Stoxx 50",
    "^N225": "Nikkei 225",
    "^TOPX": "TOPIX",
    "9816.T": "TSE Growth Core ETF",
    "1343.T": "TSE REIT ETF",
    "^HSI": "Hang Seng",
    "000001.SS": "Shanghai Composite",
    "^STI": "Straits Times",
    "^IRX": "US 3M T-Bill",
    "^TNX": "US 10Y Treasury",
    "^JGB10Y": "Japan 10Y",
    "^SG10Y=RR": "Singapore 10Y",
    "^DE10Y=X": "Germany 10Y Bund",
    "JPY=X": "USD/JPY",
    "EURJPY=X": "EUR/JPY",
    "GBPJPY=X": "GBP/JPY",
    "SGDJPY=X": "SGD/JPY",
    "CHFJPY=X": "CHF/JPY",
    "IXN": "Global Tech ETF",
    "IXG": "Global Financials ETF",
    "IXJ": "Global Healthcare ETF",
    "IXC": "Global Energy ETF",
    "MXI": "Global Materials ETF",
    "EXI": "Global Industrials ETF",
    "RXI": "Global Consumer Discretionary ETF",
    "KXI": "Global Consumer Staples ETF",
    "IXP": "Global Communication ETF",
    "JXI": "Global Utilities ETF",
    "RWO": "Global Real Estate ETF",
    "IWVL.L": "World Value Factor",
    "IWFG.L": "World Growth Factor",
    "IWFM.L": "World Momentum Factor",
    "IWQU.L": "World Quality Factor",
    "ACWV": "World Min Volatility"
}

REFRESH_INTERVAL = 900  # seconds
