# List of tickers grouped by asset class and region
TICKER_GROUPS = {
    "Global Equity": {
        "^GSPC": "S&P 500",
        "^IXIC": "NASDAQ Composite",
        "^RUT": "Russell 2000",
        "^FTSE": "FTSE 100",
        "^STOXX50E": "Euro Stoxx 50",
        "^N225": "Nikkei 225",
        "^TOPX": "TOPIX",
        "9816.T": "TSE Growth Core ETF",
        "1343.T": "TSE REIT ETF",
        "^HSI": "Hang Seng",
        "000001.SS": "Shanghai Composite",
        "^STI": "Straits Times",
    },
    "Interest Rate": {
        "^IRX": "US 3M T-Bill",
        "^TNX": "US 10Y Treasury",
        "^JGB10Y": "Japan 10Y Gov Bond",
        "^SG10Y=RR": "Singapore 10Y Gov Bond",
        "^DE10Y=X": "Germany 10Y Bund",
    },
    "Currency": {
        "JPY=X": "USD/JPY",
        "EURJPY=X": "EUR/JPY",
        "GBPJPY=X": "GBP/JPY",
        "SGDJPY=X": "SGD/JPY",
        "CHFJPY=X": "CHF/JPY",
    },
    "Commodity": {
        "GC=F": "Gold",
        "CL=F": "Crude Oil",
        "HG=F": "Copper",
        "BTC-USD": "Bitcoin",
    },
    "Global Sector": {
        "IXN": "Global Tech ETF",
        "IXG": "Global Financials ETF",
        "IXJ": "Global Health Care ETF",
        "IXC": "Global Energy ETF",
        "MXI": "Global Materials ETF",
        "EXI": "Global Industrials ETF",
        "RXI": "Global Cons Discretionary ETF",
        "KXI": "Global Cons Staples ETF",
        "IXP": "Global Communication Services ETF",
        "JXI": "Global Utilities ETF",
        "RWO": "Global Real Estate ETF",
    },
    "Global Factor": {
        "IWVL.L": "World Value Factor ETF",
        "IWFG.L": "World Growth Factor ETF",
        "IWFM.L": "World Momentum Factor ETF",
        "IWQU.L": "World Quality Factor ETF",
        "ACWV": "World Min Volatility ETF",
    },
    "US Sector": {
        "XLK": "US Info Tech",
        "XLF": "US Financials",
        "XLV": "US Health Care",
        "XLE": "US Energy",
        "XLB": "US Materials",
        "XLI": "US Industrials",
        "XLY": "US Cons Discretionary",
        "XLP": "US Cons Staples",
        "XLC": "US Communication Services",
        "XLU": "US Utilities",
        "XLRE": "US Real Estate",
    },
    "EU Sector": {
        "EXV3.DE": "EU Info Tech",
        "EXV1.DE": "EU Banks",
        "EXV4.DE": "EU Health Care",
        "EXH1.DE": "EU Oil & Gas",
    },
    "Japan Sector": {
        "1625.T": "JP Info Equipment",
        "1626.T": "JP IT & Services",
        "1631.T": "JP Banks",
        "1621.T": "JP Pharmaceuticals",
        "1618.T": "JP Energy Resources",
    },
    "US Factor": {
        "VLUE": "US Value",
        "IWF": "US Growth",
        "MTUM": "US Momentum",
        "QUAL": "US Quality",
        "USMV": "US Min Volatility",
    },
    "EU Factor": {
        "IEVL.L": "EU Value",
        "IEMO.L": "EU Momentum",
        "IEFQ.L": "EU Quality",
    },
    "Japan Factor": {
        "EWJV": "Japan Value",
        "2636.T": "Japan Quality",
        "1477.T": "Japan Min Volatility",
    },
}

REFRESH_INTERVAL = 900  # seconds

# Flatten list of all tickers for download
ALL_TICKERS = [t for group in TICKER_GROUPS.values() for t in group]